apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  POSTGRES_USER: "mharko"
  DB_PORT: "5432"

  EUREKA_HOST: "eureka-server"
  EUREKA_PORT: "8761"

  URL_CONFIG: "http://config-server:8081"

  KEYCLOAK_URL: "http://keycloak-service:9090"
  KEYCLOAK_ISSUER_URL: "http://192.168.39.130:31000"
  KEYCLOAK_REALM: "ToolRent"
  KEYCLOAK_CLIENT_ID: "toolrent-backend"
  KEYCLOAK_CLIENT_SECRET: "dVXW9tfHmjPMNBSEGgWI6SpDZg06YctP"

  MS_INVENTORY_TOOLS_URL: "http://inventory-service/tools"
  MS_INVENTORY_INVENTORY_URL: "http://inventory-service/inventory"

  MS_CLIENTS_URL: "http://clients-service/clients"

  MS_USERS_URL: "http://users-service/users"

  MS_AMOUNTS_URL: "http://amounts-service/amounts"

  MS_KARDEX_URL: "http://kardex-service/kardex"

  MS_LOANS_URL: "http://loans-service/loans"
